version: '3.8'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity

    network_mode: service:db

  db:
    image: mariadb:10.11
    restart: unless-stopped
    volumes: 
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=proyecto_inventario
      - MYSQL_USER=cronoflow_user
      - MYSQL_PASSWORD=cronoflow_pass

volumes:
  mariadb-data:
